on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  buidJoB:
    name: buid
    runs-on: macos-14
    steps:
      - uses: actions/checkout@main
        with:
          submodules: 'true'
      - name: Set up Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode_15.2.app/Contents/Developer
          xcode-select -p
          xcodebuild -version
      - name: Build
        run: |
          cd Demo
          pod install
          swift package BuildFFmpeg  -h
          swift run ffmpeg -h
          xcodebuild -workspace Demo.xcworkspace -scheme macOS
          xcodebuild -workspace Demo.xcworkspace -scheme iOS -sdk iphonesimulator
          # xcodebuild -workspace Demo.xcworkspace -scheme tvOS -sdk appletvsimulator
          
